routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('tax', 'TaxController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TaxController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TaxRequest;
use App\Providers\TaxProvider;
use Illuminate\Http\Request;

class TaxController extends Controller
{


    protected $result = [];
    protected $tax = 0;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // get marriage status as tax relief
        $status = $this->getRelief();
        return view('tax', compact('status'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaxRequest $request)
    {
    ///    dd($request->toArray());
        //echo '<pre/>';
        // multiple 12 (year = 12 months)
        $yearlyIncome = $request->income * 12;
        // cut with Relief
        $status = $this->getRelief();
        $relief = $status[$request->status]['value'];
        $netIncome = $yearlyIncome - $relief;
        if ($netIncome > 0) {
            $taxScheme = $this->getScheme();
            $this->taxCalculation($taxScheme, $netIncome);
        } else {
            $netIncome = 0;
        }
        $req = [
            'name' => $request->name,
            'status' => $status[$request->status]['name'],
            'income' => $this->formatedRupiah($request->income),
            'yearlyIncome' => $this->formatedRupiah($yearlyIncome),
            'taxableIncome' => $this->formatedRupiah($netIncome)
        ];
        $result = [
            'request' => $req,
            'totalTax' => $this->tax,
            'tax' => [
                'total' => $this->tax,
                'totalFormated' => $this->formatedRupiah($this->tax),
            ],
            'relief' => $this->formatedRupiah($relief),
            'result' => $this->result
        ];
        return redirect()->route('tax.index')
            ->with('result', $result);
    }

    /**
     * Recursive Function for Tax Calculation
     *
     * @param  Array  $taxScheme
     * @param Int  $netIncome
     * @param Int  $inc = 0
     * @return self
     */
    private function taxCalculation($taxScheme, $netIncome, $inc = 0)
    {
        if (isset($taxScheme[$inc])) {
            $curentScheme = $taxScheme[$inc];
            $percent = $curentScheme['percent'];
            $curValue = $curentScheme['value'];
            /*
             set minimum level
             $nextValue mean floor limit
            */
            $befValue = 0;
            if (isset($taxScheme[$inc-1])) {
                $befValue = $taxScheme[$inc-1]['value'];
            }
            $netIncome = $netIncome - ($curValue - $befValue);
            /*
             set maximum level
             $nextValue mean ceil limit
            */
            $nextValue = $netIncome;
            // its mean maximum (last condition), mean unlimited
            if (isset($taxScheme[$inc+1])) {
                $nextValue = $taxScheme[$inc+1]['value'];
            }
            // no need continue if net income is below 0
            if ($netIncome <= 0) {
                return;
            }
            // set taxIncome = max level - current scheme
            $taxIncome = $nextValue - $curValue;
            /*
                $netIncome < $taxIncome mean it max loop
                $taxIncome <= 0 mean if tax is below 0
                then use $netIncome as $taxIncome
            */
            $continue = true;
            if ($netIncome < $taxIncome || $taxIncome <= 0) {
                // make stopper here, mean this is last loop
                if ($taxIncome <= 0) {
                    $continue = false;
                }
                $taxIncome = $netIncome;
            }
            $tax = $taxIncome * $percent / 100;
            // sett total tax
            $this->tax += $tax;
            $this->result[] = [
                'income' => $netIncome,
                'taxIncome' => $taxIncome,
                'percentage' => $percent,
                'taxLevel' => $inc+1,
                'tax' => $tax,
                'taxIncomeFormat' => $this->formatedRupiah($taxIncome),
                'incomeFormat' => $this->formatedRupiah($netIncome),
                'taxFormat' => $this->formatedRupiah($tax)
            ];
            if ($continue) {
                $inc++;
                return $this->taxCalculation($taxScheme, $netIncome, $inc);
            }
        }
    }

    private function formatedRupiah($arg)
    {
        return 'Rp '.number_format($arg);
    }

    private function getRelief()
    {
        return config('tax.relief');
    }

    private function getScheme()
    {
        // reorder taxScheme, to set if invalid / wrong min max
        $taxScheme = config('tax.scheme');
        $tmp = [];
        $scheme = [];
        foreach ($taxScheme as $key => $value) {
            $tmp[$value['value']][] = $key;
        }
        // sort key by ASC
        ksort($tmp);
        foreach ($tmp as $val) {
            foreach ($val as $key => $value) {
                $scheme[] = $taxScheme[$value];
            }
        }
        return $scheme;
    }
}

resources/views/result.blade.php
@if (session('result'))
    @php
        $sess = session('result');
        $request = $sess['request'];
        $result = $sess['result'];
    @endphp
    <hr/>
    <h3>User</h3>
    <div class="media">
        <div class="d-flex flex-column counters">
            Name : {{ $request['name'] }}
        </div>
    </div>
    <div class="media">
        <div class="d-flex flex-column counters">
            Marrieage status : {{ $request['status']}}
        </div>
    </div>
    <div class="media">
        <div class="d-flex flex-column counters">
            Income per Month : {{ $request['income'] }}
        </div>
    </div>
    <div class="media">
        <div class="d-flex flex-column counters">
            Yearly Income : {{ $request['yearlyIncome'] }}
        </div>
    </div>
    <div class="media">
        <div class="d-flex flex-column counters">
            Non-Taxable Income : {{ $sess['relief'] }}
        </div>
    </div>
    <div class="media">
        <div class="d-flex flex-column counters">
            Taxable Income : {{ $request['taxableIncome'] }}
        </div>
    </div>
    <div>&nbsp;</div>
    <h3>Tax Calculation</h3>
    @foreach ($result as $key => $value)
    <div class="media">
        <div class="d-flex flex-column counters">
            Taxable income lvl {{ $value['taxLevel'] }}: {{ $value['taxIncomeFormat'] }} * {{ $value['percentage'] }}% = {{ $value['taxFormat'] }}
        </div>
    </div>
    @endforeach
    <div class="media">
        <div class="d-flex flex-column counters">
            Total Tax : {{ $sess['tax']['totalFormated'] }}
        </div>
    </div>
@endif

resources/views/tax.blade.php
<!doctype html>
<?php
 ?>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
        <main class="py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">
                                <div class="d-flex align-items-center">
                                    <h2>Calculate Tax</h2>
                                </div>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('tax.store') }}" method="post">
@csrf
                                    <div class="form-group row">
                                        <label for="tax-name" class="col-md-5">Name</label>
                                        <div class="col-md-7">
                                            <input type="text" required name="name" id="tax-name" value="{{ old('name') }}" class="form-control {{ $errors->has('name') ? 'is-invalid': '' }}" placeholder="Name">
@if ($errors->has('name'))
                                            <div class="invalid-feedback d-block">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </div>
@endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="tax-status" class="col-md-5">Marrieage status</label>
                                        <div class="col-md-7">
                                            <select name="status" required id="tax-status" class="form-control {{ $errors->has('status') ? 'is-invalid': '' }}" >
@foreach ($status as $key => $value)
                                                <option value="{{ $key }}">{{ $value['name'] }}</option>
@endforeach
                                            </select>
@if ($errors->has('status'))
                                            <div class="invalid-feedback d-block">
                                                <strong>{{ $errors->first('status') }}</strong>
                                            </div>
@endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="tax-income" class="col-md-5">Income per Month</label>
                                        <div class="col-md-7 input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">RP</span>
                                            </div>
                                            <input type="number" required name="income" id="tax-income" value="{{ old('income') }}" class="form-control {{ $errors->has('income') ? 'is-invalid': '' }}" placeholder="3.000.000">
@if ($errors->has('name'))
                                            <div class="invalid-feedback d-block">
                                                <strong>{{ $errors->first('income') }}</strong>
                                            </div>
@endif
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-outline-primary btn-lg">Calculate</button>
                                    </div>
                                </form>
@include ('result')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</body>
</html>